### ISSUE TITLE
Parameter Source

### ISSUE THREAD

**Issue by Shackmeister** [KiCad/Pin_Headers.pretty#23]
Hey People
@SchrodingersGat @jkriege2 @poeschlr @pointhi 
Im having trouble finding the sources of the scripted Pin_Header footprints
I believe the are generated using this script:
https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/pin-headers_socket-strips/make_pin_headers.py
I cant find any connectors matching the footprints of the angled ones

**Comment by jkriege2** [comment]
Here's the original PR with references:
https://github.com/KiCad/Pin_Headers.pretty/pull/17

Also e.g. these fit approximaterly:
http://katalog.we-online.de/en/em/PHD_2_54_THT_ANGLED_PIN_HEADER_6130XX11021

Best,
JAN

**Comment by Shackmeister** [comment]
hi @jkriege2 
It seems the silkscreen is slightly off for these connectors? do you think this is enough to be worth fixing? in that case can you do it or should I give it a go?
![pin_header](https://cloud.githubusercontent.com/assets/5279723/26803252/cd1dbcd2-4a43-11e7-8e54-cc095f10a337.png)

**Comment by jkriege2** [comment]
Since I'm currently quite budy ... please have a go ... I think it should be quite easy and you'll only have to change 1-2 Parameters in the script ...

Best,
JAN

**Comment by Shackmeister** [comment]
I have now updated the script with some KLC fixes and proper offset
but I cant find the parameters used for the 1.27 set

**Comment by Shackmeister** [comment]
@jkriege2 @poeschlr @SchrodingersGat 
Hey guys can you please comment on the placement of the %R on the Fab layer?
![angled_pinheader](https://user-images.githubusercontent.com/5279723/27226728-aad75128-52a0-11e7-9bde-f2173d93a6f4.png)
![straight_pinheader](https://user-images.githubusercontent.com/5279723/27226730-ad373b4a-52a0-11e7-8ca5-7eedb34054ef.png)

**Comment by poeschlr** [comment]
My suggestions:
For angled version: Remove the "inner" details of the connecting body and place the reference there. (rotated by 90 degree)
![27226728-aad75128-52a0-11e7-9bde-f2173d93a6f4](https://user-images.githubusercontent.com/18327350/27226976-bd40d48c-52a1-11e7-9e60-2bc17f7a3962.png)
Place the reference within the body (rotated by 90 degree).
![27226730-ad373b4a-52a0-11e7-8ca5-7eedb34054ef](https://user-images.githubusercontent.com/18327350/27226977-bd602e18-52a1-11e7-9e39-61e2676f7a20.png)

If you have a pin 1 marker on silk, you also need one on fab.

**Comment by Shackmeister** [comment]
1. Kinda like the "inner liner" between the pins (the ones seperated by 2.54mm) but I can get rid of them 
2. I thought the reference should be avoided on pads? 
3. Any specific pin 1 marker you would suggest? Chamfered corner?

**Comment by SchrodingersGat** [comment]
@poeschlr suggestions are good. The Fab drawings for angled connectors should be simplified and I agree with his suggested placements.

> I thought the reference should be avoided on pads?

That is true for the **Silkscreen** layer but the Fab layer is virtual and does not get obstructed by pads.

**Comment by poeschlr** [comment]
> Any specific pin 1 marker you would suggest? Chamfered corner?

I would go with a chamfered corner
![27226976-bd40d48c-52a1-11e7-9e60-2bc17f7a3962](https://user-images.githubusercontent.com/18327350/27228196-e2c6b708-52a6-11e7-8001-77b03eb2e18c.png)
![27226977-bd602e18-52a1-11e7-9e39-61e2676f7a20](https://user-images.githubusercontent.com/18327350/27228195-e2c530cc-52a6-11e7-8360-896fd4cfab52.png)

**Comment by Shackmeister** [comment]
lets see if we're on the same page, scripts has been updated
![pinheaders](https://user-images.githubusercontent.com/5279723/27231437-e9ce4b40-52b2-11e7-940a-864b42d8d1b4.png)

**Comment by poeschlr** [comment]
Looks good to me.

**Comment by Shackmeister** [comment]
Any other comments before I finish up the script?

**Comment by poeschlr** [comment]
Connectors have a courtyard clearance of 0.5mm. It looks a bit smaller on the screenshot. (But in reality i can't tell without the footprint files.)

**Comment by Shackmeister** [comment]
PR added :)
https://github.com/KiCad/Pin_Headers.pretty/pull/24
