### ISSUE TITLE
Add inverted footprints

### ISSUE THREAD

**Issue by pointhi** [KiCad/Pin_Headers.pretty#25]
When someone wants to create for example stacked boards, 2-row connectors creates the problem of having the pin number on the wrong site, when placed correctly onto the pcb (back of pcb).

Probably we should add inverted models (I think inside a new repo) with correct pin numbers to allow such usecase

**Comment by SchrodingersGat** [comment]
@pointhi don't the Pin-Headers and Socket_Strips footprints have inverted pin numbers to address this problem?

**Comment by hackscribble** [comment]
This also applies to some of the connector libraries - e.g. Molex SlimStack are intended for stacked boards (as the name suggests :wink:)

**Comment by pointhi** [comment]
>  don't the Pin-Headers and Socket_Strips footprints have inverted pin numbers to address this problem?

That doesn't help when the doughter board uses a different pinning

**Comment by SchrodingersGat** [comment]
@pointhi you will have to open this issue at the new repo!
